namespace: flask-demo-envfile-in-pip-c
configMapGenerator:
- name: flask-demo-envfile-in-pip-c-master-env
  literals:
  - FOO=Bar
  - Bear=Bear
  - TestAdd=newAdd
  - AddNewTest=111111111111111111111111
  - test2=2222222222222222222
generatorOptions:
  disableNameSuffixHash: true
#configMapGenerator:
#- name: flask-demo-envfile-in-pip-c-master-env
#  files:
#  - ./app.env
